import Link from 'next/link';
import BuyerFAQ from '../../components/BuyerFAQ';

export const metadata = {
  title: 'AI Short Drama Ad Production: Brief to Delivery',
  description: 'How AI short drama ads are planned and produced: product references, script approval, character continuity, product checks and vertical video delivery.',
  alternates: { canonical: '/ai-short-drama-ads' },
  openGraph: { title: 'AI Short Drama Ad Production | Moon Ocean Studio', description: 'A practical workflow for product-led short drama creative.', url: '/ai-short-drama-ads' }
};
const stages = [
  ['1. Define the brief', 'Product photos or footage, the product URL, logo, audience, campaign goal, target platforms, budget and deadline. Identify the details the video must preserve.'],
  ['2. Approve the story', 'Choose one concept, then review the script, scene order and product role. Confirm where the product is visible and how the video leads to the next action.'],
  ['3. Lock the references', 'Use approved character, outfit, location and product references across scenes. Review the visual direction before generating the full sequence.'],
  ['4. Produce and check', 'Review faces, clothing, dialogue and shot continuity. Compare product shape, color, logos and small details against the supplied assets. A reference image helps; it does not replace review.'],
  ['5. Finish the agreed versions', 'Edit the selected shots, sync dialogue and captions, and prepare the versions in the quote. Confirm the target ad placements and check their current specifications before delivery.']
];
const faqs = [
  { question: 'What should I send for a jewelry or watch ad?', answer: 'Send clear product photos from several angles, a product URL, your logo and brand references. Include close-ups of details that must stay accurate, such as stone layout, chain thickness, clasp, dial or hardware.' },
  { question: 'How do you keep characters consistent?', answer: 'Use approved character and wardrobe references across scenes, then review each selected shot. Multi-scene continuity is a production check, not a guarantee that every generated clip will be correct.' },
  { question: 'What if AI changes the product or logo?', answer: 'Compare the shot with the product reference before approval. Depending on the scene, correction can mean replacing the shot, compositing real product imagery or adding the logo in post. The required accuracy and correction scope should be agreed before production.' },
  { question: 'Can I request captions and a version without music?', answer: 'Yes, include the exact versions in the brief and quote: captioned, clean without captions, or dialogue and effects without background music. These are different deliverables. Separate audio tracks should be planned from the start.' },
  { question: 'How long does production take?', answer: 'Timing depends on scene complexity, product accuracy, approved versions and feedback rounds. Agree milestones for the script, visual references, first cut and revisions when requesting a production quote.' }
];
export default function Page() {
  return <main>
    <section className="hero"><div className="container"><div className="eyebrow">AI short drama production</div><h1>From Product Brief to Finished Short Drama Ad.</h1><p className="lead">Plan the story, approve the product moment and check the details before delivery. A clear scope keeps creative decisions and revisions manageable.</p><div className="actions"><Link className="btn primary" href="/contact">Send My Product</Link><Link className="btn secondary" href="/examples">Watch the Concepts</Link></div></div></section>
    <section className="section"><div className="container"><h2>The production workflow.</h2><div className="workflow-list">{stages.map(([title, body]) => <article className="card" key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className="section"><div className="container two-col"><div><div className="eyebrow">Product fidelity</div><h2>Keep the actual product recognizable.</h2></div><div className="editorial"><p>A generated scene can look convincing while changing the item you sell. Use real product imagery or footage when exact details matter, and review close-ups before approving the cut.</p><ul className="clean"><li>Jewelry: shape, stones, metal color, chain and clasp</li><li>Watches: dial, hands, markings, case and strap</li><li>Handbags: silhouette, hardware, texture and logo</li></ul><p>For mixed production, the environment can be generated while the product and logo are added from supplied assets. <a href="https://www.chipscat.com/en/blog/ai-video-with-real-products/" target="_blank" rel="noopener noreferrer">Read a studio’s explanation of the mixed workflow</a>.</p></div></div></section>
    <section id="brief" className="section"><div className="container"><h2>A brief you can copy.</h2><div className="card brief-template editorial"><p><strong>Product:</strong> Product URL, front/back/side photos, a close-up, logo files and a scale reference. List details that must not change.<br /><strong>Audience:</strong> Market, language and intended buyer.<br /><strong>Objective:</strong> Awareness, store visits or a purchase test. Name the primary outcome.<br /><strong>Story:</strong> Tone, product role, references and anything to avoid.<br /><strong>Delivery:</strong> Target runtime, platforms, aspect ratios, number of hooks, languages, captions and audio versions.<br /><strong>Scope:</strong> Budget ceiling, desired deadline, one approver, review rounds and intended usage.<br /><strong>Assets:</strong> Identify who supplies the product footage, music, voices and any licensed references.</p></div><p className="editorial">Copy these fields into <Link href="/contact">your product inquiry</Link>. The final deliverables, price and milestones are confirmed in the written quote.</p></div></section>
    <section className="section"><div className="container"><h2>Approve the decisions that are expensive to change.</h2><div className="grid"><article className="card"><h3>Script & product role</h3><p>Review the dialogue, scene order, product moment and next action before generation. Resolve brand claims and story changes here.</p></article><article className="card"><h3>References & key frames</h3><p>Check the faces, wardrobe, product details and visual direction. Mark the shots that need real product assets or post-production compositing.</p></article><article className="card"><h3>First cut & delivery</h3><p>Check continuity, pronunciation, captions, product close-ups and the agreed export versions. Consolidate feedback through the named approver.</p></article></div></div></section>
    <section className="section"><div className="container"><h2>Name each delivery version.</h2><p className="lead">Use this checklist when agreeing the quote. Include only the files your campaign needs.</p><div className="table-scroll" role="region" aria-label="Video delivery checklist" tabIndex={0}><table className="content-table"><caption>Specify versions before production begins.</caption><thead><tr><th scope="col">Deliverable</th><th scope="col">Confirm in the brief</th></tr></thead><tbody><tr><th scope="row">Captioned video</th><td>Language, spelling, caption style and safe placement.</td></tr><tr><th scope="row">Textless video</th><td>Which captions or overlays are removed. Textless does not mean music-free.</td></tr><tr><th scope="row">No-background-music version</th><td>Whether dialogue and sound effects remain. Plan separate audio tracks from the start.</td></tr><tr><th scope="row">Additional hooks or formats</th><td>Number of distinct edits and each target placement, aspect ratio and export specification.</td></tr><tr><th scope="row">Optional source materials</th><td>Whether subtitle files, audio stems or editable project files are included. Do not assume they accompany the final video.</td></tr></tbody></table></div></div></section>
    <section className="section"><div className="container two-col"><div><h2>Record usage with the brief.</h2></div><div className="editorial"><p>List intended placements, territories and usage duration, along with the source of product imagery, music, voices and character references. Confirm any third-party conditions before production and delivery.</p><p>For inspiration, describe the story mechanism you want to explore and develop an original script. Identify any material that requires permission instead of treating a reference video as an asset ready to reuse.</p></div></div></section>
    <section className="section"><div className="container"><h2>Production questions.</h2><BuyerFAQ items={faqs} /><p className="editorial">Next: <Link href="/guides/testing-short-drama-ads">test the finished creative against your current ads</Link>, or plan <Link href="/branded-short-drama">a recurring branded story</Link>.</p></div></section>
  </main>;
}
